function T = generate_i2_pure_fir_coeffs(varargin)
% Generate the I2 monolithic x32 pure-FIR coefficients from I0's cascade.
% The emitted SystemVerilog include is a source asset, not a simulation dump.

  cfg = local_cfg();
  for k = 1:2:numel(varargin)
    cfg.(varargin{k}) = varargin{k + 1};
  end

  hb = halfband_interp_coeff(47);
  hcic = cic_interp_impulse(8, 4);
  hcomp = cic_comp_coeff(63, 8, 4);
  h = 1;
  h = cascade(h, 1, hb, 2);
  h = cascade(h, 2, hb, 2);
  h = cascade(h, 4, hcic, 8);
  h = conv(h, hcomp);
  hq = round(h(:) * 2^cfg.coeff_frac);
  if any(abs(hq) > (2^(cfg.coeff_w - 1) - 1))
    error('I2 coefficient width is insufficient');
  end
  hq = int64(hq);
  if numel(hq) ~= 1195
    error('Unexpected I2 tap count: %d', numel(hq));
  end

  emit_svh(cfg.svh_path, hq, cfg.coeff_w);
  T = table((0:numel(hq)-1).', hq, 'VariableNames', {'tap', 'coeff_q2_16'});
  ensure_parent(cfg.csv_path);
  writetable(T, cfg.csv_path);
end

function cfg = local_cfg()
  repo = fileparts(fileparts(fileparts(mfilename('fullpath'))));
  cfg.coeff_w = 18;
  cfg.coeff_frac = 16;
  cfg.svh_path = fullfile(repo, 'rtl', 'interp', 'dsm_interp_i2_coeffs.svh');
  cfg.csv_path = fullfile(repo, 'matlab', 'out', 'frontend_dsm_pareto', 'i2_coefficients_q2_16.csv');
end

function emit_svh(path, hq, coeff_w)
  [folder, ~, ~] = fileparts(path);
  if ~exist(folder, 'dir'), mkdir(folder); end
  fid = fopen(path, 'w');
  if fid == -1, error('Cannot write %s', path); end
  fprintf(fid, '// Generated by generate_i2_pure_fir_coeffs.m; do not hand-edit.\n');
  fprintf(fid, 'function automatic logic signed [%d:0] coeff_i2(input int idx);\n', coeff_w-1);
  fprintf(fid, '  begin\n    case (idx)\n');
  for k = 1:numel(hq)
    if hq(k) < 0
      value = sprintf('-%d''sd%d', coeff_w, abs(hq(k)));
    else
      value = sprintf('%d''sd%d', coeff_w, hq(k));
    end
    fprintf(fid, '      %d: coeff_i2 = %s;\n', k-1, value);
  end
  fprintf(fid, '      default: coeff_i2 = ''0;\n    endcase\n  end\nendfunction\n');
  fclose(fid);
end

function ensure_parent(path)
  [folder, ~, ~] = fileparts(path);
  if ~exist(folder, 'dir'), mkdir(folder); end
end

function h = cascade(h0, ~, hstage, L)
  up = zeros(1, (numel(h0)-1)*L + 1);
  up(1:L:end) = h0;
  h = conv(up, hstage);
end

function h = halfband_interp_coeff(ntaps)
  mid = (ntaps - 1) / 2;
  n = (0:ntaps-1) - mid;
  h = sinc_local(0.5 * n) .* hamming_local(ntaps);
  h(abs(h) < 1e-14) = 0;
  h = h * (2 / sum(h));
end

function h = cic_interp_impulse(rate, order)
  h = ones(1, rate);
  for k = 2:order, h = conv(h, ones(1, rate)); end
  h = h / rate^(order - 1);
end

function h = cic_comp_coeff(ntaps, rate, order)
  f = linspace(0, 0.5, 512).';
  cic = abs(sin(pi*f*rate) ./ (rate * sin(pi*f)));
  cic(1) = 1; cic = cic .^ order;
  desired = zeros(size(f)); pass = f <= 0.025; trans = f > 0.025 & f < 0.060;
  desired(pass) = 1 ./ max(cic(pass), 0.08);
  desired(trans) = linspace(desired(find(pass, 1, 'last')), 0, nnz(trans)).';
  weight = ones(size(f)); weight(pass) = 8;
  h = fir_ls_linear_phase(ntaps, f, desired, weight); h = h / sum(h);
end

function h = fir_ls_linear_phase(ntaps, f, desired, weight)
  mid = (ntaps - 1) / 2; k = 0:mid; A = cos(2*pi*f*k);
  c = (A' * diag(weight) * A) \ (A' * diag(weight) * desired);
  h = zeros(1, ntaps); h(mid+1) = c(1);
  for n = 1:mid
    h(mid+1-n) = c(n+1)/2; h(mid+1+n) = c(n+1)/2;
  end
end

function y = sinc_local(x)
  y = ones(size(x)); nz = abs(x) > 1e-12;
  y(nz) = sin(pi*x(nz)) ./ (pi*x(nz));
end

function w = hamming_local(n)
  k = 0:n-1; w = 0.54 - 0.46*cos(2*pi*k/(n-1));
end
