// Generated by generate_memory_tinyml_tree_sources.py; do not edit.
`timescale 1ns/1ps
`default_nettype none

module dpd_tinyml_tree (
  input wire feature_valid,
  input wire signed [(13*32)-1:0] features_q20,
  output reg [2:0] seed_package,
  output reg direct,
  output wire fallback_required,
  output wire local_search_required,
  output reg [3:0] decision_path,
  output reg [2:0] decision_path_length,
  output reg out_of_distribution
);

  localparam [2:0] FALLBACK_PACKAGE = 3'd6;

  wire signed [31:0] f0 = features_q20[(0*32) +: 32];
  wire signed [31:0] f1 = features_q20[(1*32) +: 32];
  wire signed [31:0] f2 = features_q20[(2*32) +: 32];
  wire signed [31:0] f3 = features_q20[(3*32) +: 32];
  wire signed [31:0] f4 = features_q20[(4*32) +: 32];
  wire signed [31:0] f5 = features_q20[(5*32) +: 32];
  wire signed [31:0] f6 = features_q20[(6*32) +: 32];
  wire signed [31:0] f7 = features_q20[(7*32) +: 32];
  wire signed [31:0] f8 = features_q20[(8*32) +: 32];
  wire signed [31:0] f9 = features_q20[(9*32) +: 32];
  wire signed [31:0] f10 = features_q20[(10*32) +: 32];
  wire signed [31:0] f11 = features_q20[(11*32) +: 32];
  wire signed [31:0] f12 = features_q20[(12*32) +: 32];

  wire leaf_0_envelope =
      (f0 >= 32'sd262144) && (f0 <= 32'sd1048576) &&
      (f1 >= 32'sd524288) && (f1 <= 32'sd1048576) &&
      (f2 >= 32'sd608174) && (f2 <= 32'sd608174) &&
      (f3 >= 32'sd308405) && (f3 <= 32'sd1048576) &&
      (f4 >= 32'sd1054364) && (f4 <= 32'sd1064422) &&
      (f5 >= 32'sd2320750) && (f5 <= 32'sd3171213) &&
      (f6 >= 32'sd38822) && (f6 <= 32'sd92686) &&
      (f7 >= 32'sd349216) && (f7 <= 32'sd386375) &&
      (f8 >= 32'sd2064775) && (f8 <= 32'sd59310860) &&
      (f9 >= 32'sd22610) && (f9 <= 32'sd389807) &&
      (f10 >= 32'sd0) && (f10 <= 32'sd0) &&
      (f11 >= 32'sd0) && (f11 <= 32'sd0) &&
      (f12 >= 32'sd38822) && (f12 <= 32'sd92686);

  wire leaf_11_envelope =
      (f0 >= 32'sd1048576) && (f0 <= 32'sd1048576) &&
      (f1 >= 32'sd524288) && (f1 <= 32'sd524288) &&
      (f2 >= 32'sd734003) && (f2 <= 32'sd734003) &&
      (f3 >= 32'sd308405) && (f3 <= 32'sd1048576) &&
      (f4 >= 32'sd1061107) && (f4 <= 32'sd1066450) &&
      (f5 >= 32'sd2495721) && (f5 <= 32'sd2653496) &&
      (f6 >= 32'sd52420) && (f6 <= 32'sd97863) &&
      (f7 >= 32'sd361357) && (f7 <= 32'sd367264) &&
      (f8 >= 32'sd3728765) && (f8 <= 32'sd5592713) &&
      (f9 >= 32'sd151299) && (f9 <= 32'sd353921) &&
      (f10 >= 32'sd0) && (f10 <= 32'sd0) &&
      (f11 >= 32'sd0) && (f11 <= 32'sd0) &&
      (f12 >= 32'sd52420) && (f12 <= 32'sd97863);

  assign fallback_required = !direct;
  assign local_search_required = !direct;

  always @* begin
    seed_package = FALLBACK_PACKAGE;
    direct = 1'b0;
    decision_path = 4'd0;
    decision_path_length = 3'd0;
    out_of_distribution = !feature_valid ||
        (f0 < 32'sd262144) || (f0 > 32'sd1048576) ||
        (f1 < 32'sd524288) || (f1 > 32'sd1048576) ||
        (f2 < 32'sd608174) || (f2 > 32'sd734003) ||
        (f3 < 32'sd308405) || (f3 > 32'sd1048576) ||
        (f4 < 32'sd1054364) || (f4 > 32'sd1070144) ||
        (f5 < 32'sd2187435) || (f5 > 32'sd3171213) ||
        (f6 < 32'sd38822) || (f6 > 32'sd105054) ||
        (f7 < 32'sd347382) || (f7 > 32'sd386375) ||
        (f8 < 32'sd1568684) || (f8 > 32'sd105200450) ||
        (f9 < 32'sd15807) || (f9 > 32'sd436535) ||
        (f10 < 32'sd0) || (f10 > 32'sd0) ||
        (f11 < 32'sd0) || (f11 > 32'sd0) ||
        (f12 < 32'sd38822) || (f12 > 32'sd105054);

    if (!out_of_distribution) begin
      if (f2 <= 32'sd608174) begin
        decision_path = 4'd0;
        decision_path_length = 3'd1;
        if (leaf_0_envelope) begin
          seed_package = 3'd1;
          direct = 1'b1;
        end else begin
          out_of_distribution = 1'b1;
        end
      end else begin
        if (f8 <= 32'sd5592713) begin
          if (f0 <= 32'sd262144) begin
            decision_path = 4'd4;
            decision_path_length = 3'd3;
          end else begin
            if (f7 <= 32'sd355196) begin
              decision_path = 4'd10;
              decision_path_length = 3'd4;
            end else begin
              decision_path = 4'd11;
              decision_path_length = 3'd4;
              if (leaf_11_envelope) begin
                seed_package = 3'd4;
                direct = 1'b1;
              end else begin
                out_of_distribution = 1'b1;
              end
            end
          end
        end else begin
          if (f6 <= 32'sd81615) begin
            if (f7 <= 32'sd354048) begin
              decision_path = 4'd12;
              decision_path_length = 3'd4;
            end else begin
              decision_path = 4'd13;
              decision_path_length = 3'd4;
            end
          end else begin
            decision_path = 4'd7;
            decision_path_length = 3'd3;
          end
        end
      end
    end
  end

endmodule

`default_nettype wire
