#!/usr/bin/env python3
"""Generate a fail-closed PS policy header from blind PA evidence."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blind-report", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    args = parser.parse_args()
    with args.blind_report.open(encoding="ascii") as handle:
        report = json.load(handle)
    violations = int(report["seed_safety_violations"])
    promoted = bool(report["promotion_allowed"])
    args.header.parent.mkdir(parents=True, exist_ok=True)
    with args.header.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("#ifndef DPD_TINYML_HIERARCHY_POLICY_H\n")
        handle.write("#define DPD_TINYML_HIERARCHY_POLICY_H\n\n")
        handle.write("/* Generated by finalize_memory_tinyml_hierarchy_policy.py; do not edit. */\n")
        handle.write("/* Direct execution is permanently disabled for this policy contract. */\n")
        handle.write(f"#define DPD_TINYML_HIERARCHY_POLICY_AVAILABLE {1 if promoted else 0}U\n")
        handle.write("#define DPD_TINYML_HIERARCHY_POLICY_DIRECT_ALLOWED 0U\n")
        handle.write("#define DPD_TINYML_HIERARCHY_POLICY_LOCAL_CANDIDATES 14U\n")
        handle.write("#define DPD_TINYML_HIERARCHY_POLICY_ACTIVE_TAPS 4U\n")
        handle.write(f"#define DPD_TINYML_HIERARCHY_BLIND_CONDITIONS {int(report['blind_conditions'])}U\n")
        handle.write(f"#define DPD_TINYML_HIERARCHY_BLIND_SEED_VIOLATIONS {violations}U\n")
        handle.write("\n#endif /* DPD_TINYML_HIERARCHY_POLICY_H */\n")
    state = "promoted" if promoted else "blocked"
    print(f"Generated {state} TinyML hierarchy policy header; blind seed violations={violations}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
