#!/usr/bin/env python3
"""Generate the PS waveform-LUT fallback for the observer-v2 hierarchy."""

from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path

from evaluate_memory_tinyml_loso import FALLBACK, read_conditions


def write_header(path: Path, conditions: list[dict[str, object]]) -> None:
    rows = []
    for waveform in sorted({str(row["waveform_id"]) for row in conditions}):
        group = [row for row in conditions if str(row["waveform_id"]) == waveform]
        labels = [int(row["label"]) for row in group if int(row["label"]) != FALLBACK]
        package = Counter(labels).most_common(1)[0][0] if labels else FALLBACK
        first = group[0]
        rows.append((round(float(first["feature"][0]) * 64.0),
                     round(float(first["feature"][1]) * 40000.0),
                     round(float(first["feature"][2]) * 1000000.0), package))
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("#ifndef DPD_TINYML_LUT_V2_H\n#define DPD_TINYML_LUT_V2_H\n\n")
        handle.write("/* Generated by generate_memory_tinyml_lut_header.py; do not edit. */\n")
        handle.write("#define DPD_TINYML_LUT_V2_AVAILABLE 1U\n")
        handle.write(f"#define DPD_TINYML_LUT_V2_ROWS {len(rows)}U\n\n")
        handle.write("static const unsigned dsm_dpd_tinyml_lut_v2[DPD_TINYML_LUT_V2_ROWS][4] = {\n")
        for qam, bandwidth_khz, backoff_ppm, package in rows:
            handle.write(f"    {{{qam}U, {bandwidth_khz}U, {backoff_ppm}U, {package}U}},\n")
        handle.write("};\n\n#endif /* DPD_TINYML_LUT_V2_H */\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    args = parser.parse_args()
    conditions = read_conditions(args.input)
    write_header(args.header, conditions)
    print(f"Generated observer-v2 LUT fallback header with {len({str(row['waveform_id']) for row in conditions})} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
