#!/usr/bin/env python3
"""Generate a compact, reproducible memory-DPD ILA board vector package."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def signed16(value: int) -> int:
    value &= 0xFFFF
    return value - 0x10000 if value & 0x8000 else value


def read_inputs(path: Path) -> list[tuple[int, int, int]]:
    with path.open(newline="", encoding="ascii") as handle:
        return [(int(row["i_q1_15"]), int(row["q_q1_15"]), int(row["last"]))
                for row in csv.DictReader(handle)]


def read_package(header: Path, package_index: int) -> list[int]:
    text = header.read_text(encoding="ascii")
    table = re.search(r"dsm_dpd_tinyml_mp_packages.*?=\s*\{(.*?)\n\};", text, re.S)
    if table is None:
        raise ValueError(f"memory-package table not found: {header}")
    rows = re.findall(r"\{([^{}]+)\}", table.group(1))
    if not 0 <= package_index < len(rows):
        raise ValueError(f"package index {package_index} outside 0..{len(rows) - 1}")
    words = [int(value, 16) for value in re.findall(r"0x([0-9A-Fa-f]+)U", rows[package_index])]
    if len(words) != 12:
        raise ValueError(f"expected 12 memory coefficients, got {len(words)}")
    return words


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_waveform_header(path: Path, samples: list[tuple[int, int, int]]) -> None:
    words = [((q & 0xFFFF) << 16) | (i & 0xFFFF) for i, q, _ in samples]
    lines = [
        "#ifndef ILA_GOLDEN_WAVEFORM_H",
        "#define ILA_GOLDEN_WAVEFORM_H",
        "",
        "/* Generated by generate_ila_golden.py; do not edit manually. */",
        "#define DSM_DPD_TX_WAVEFORM_AVAILABLE 1U",
        "#define DSM_DPD_TX_WAVEFORM_QAM 0U",
        "#define DSM_DPD_TX_WAVEFORM_USED_SUBCARRIERS 0U",
        "#define DSM_DPD_TX_WAVEFORM_INPUT_BACKOFF_PPM 0U",
        "#define DSM_DPD_TX_WAVEFORM_FFT_SIZE 0U",
        "#define DSM_DPD_TX_WAVEFORM_SEED 0U",
        f"#define DSM_DPD_TX_WAVEFORM_WORDS {len(words)}U",
        "",
        "static const u32 dsm_dpd_tx_waveform_words[DSM_DPD_TX_WAVEFORM_WORDS] = {",
    ]
    for offset in range(0, len(words), 8):
        lines.append("    " + ", ".join(f"0x{word:08X}U" for word in words[offset:offset + 8]) + ",")
    lines += ["};", "", "#endif /* ILA_GOLDEN_WAVEFORM_H */", ""]
    path.write_text("\n".join(lines), encoding="ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", type=Path,
                        default=repo_root() / "fpga" / "zu15eg" / "out" / "ila_golden_memory_pkg0")
    parser.add_argument("--header", type=Path,
                        default=repo_root() / "fpga" / "zu15eg" / "baremetal" / "src" / "ila_golden_waveform.h")
    parser.add_argument("--package-index", type=int, default=0)
    args = parser.parse_args()

    root = repo_root()
    sys.path.insert(0, str(root / "uvm_verif" / "refmodel" / "python"))
    from dsm_refmodel import ComplexCoeff, TxBpEf2Model, interp_frontend, memory_poly

    input_path = root / "uvm_verif" / "refmodel" / "python" / "out" / "memory_dpd_system_input.csv"
    package_path = root / "fpga" / "zu15eg" / "baremetal" / "src" / "dpd_tinyml_packages_v2.h"
    samples = read_inputs(input_path)
    words = read_package(package_path, args.package_index)
    c1 = [ComplexCoeff(signed16(word), signed16(word >> 16)) for word in words[0::3]]
    c3 = [ComplexCoeff(signed16(word), signed16(word >> 16)) for word in words[1::3]]
    c5 = [ComplexCoeff(signed16(word), signed16(word >> 16)) for word in words[2::3]]
    dpd_i, dpd_q, saturated = memory_poly(
        [item[0] for item in samples], [item[1] for item in samples], c1, c3, c5, active_taps=4,
    )
    if any(saturated):
        raise RuntimeError("golden input unexpectedly saturates the memory-DPD output")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    args.header.parent.mkdir(parents=True, exist_ok=True)
    write_waveform_header(args.header, samples)
    board_header = args.out_dir / "ila_golden_waveform.h"
    write_waveform_header(board_header, samples)

    input_out = args.out_dir / "input_iq.csv"
    with input_out.open("w", newline="", encoding="ascii") as handle:
        writer = csv.writer(handle)
        writer.writerow(("n", "i_q1_15", "q_q1_15", "last", "packed_dma_word"))
        for index, (i_value, q_value, last) in enumerate(samples):
            packed = ((q_value & 0xFFFF) << 16) | (i_value & 0xFFFF)
            writer.writerow((index, i_value, q_value, last, f"0x{packed:08X}"))

    coeff_out = args.out_dir / "memory_dpd_coeff.csv"
    with coeff_out.open("w", newline="", encoding="ascii") as handle:
        writer = csv.writer(handle)
        writer.writerow(("tap", "order", "word", "real_q2_14", "imag_q2_14"))
        for tap in range(4):
            for order, word in zip(("C1", "C3", "C5"), words[tap * 3:tap * 3 + 3]):
                writer.writerow((tap, order, f"0x{word:08X}", signed16(word), signed16(word >> 16)))

    expected_out = args.out_dir / "expected_rf.csv"
    model = TxBpEf2Model()
    with expected_out.open("w", newline="", encoding="ascii") as handle:
        writer = csv.writer(handle)
        writer.writerow(("n", "rf_bit", "rf_signed", "phase", "if_sample", "dpd_i_q1_15", "dpd_q_q1_15"))
        index = 0
        for i_value, q_value in zip(interp_frontend(dpd_i, mode=4), interp_frontend(dpd_q, mode=4)):
            step = model.step(i_value, q_value)
            writer.writerow((index, step.rf_bit, step.rf_signed, step.phase, step.if_sample, i_value, q_value))
            index += 1

    manifest = {
        "format": "dsm_ip_ila_golden_v1",
        "sku": {
            "algorithm": 3,
            "duc_mode": 3,
            "interp_mode": 4,
            "memory_dpd_taps": 4,
            "memory_dpd_orders": [1, 3, 5],
            "clock_hz": 100000000,
        },
        "memory_dpd_package_index": args.package_index,
        "input_samples": len(samples),
        "expected_rf_samples": index,
        "register_snapshot": {
            "ALGORITHM": "0x00000003",
            "DUC_MODE": "0x00000003",
            "INTERP_MODE": "0x00000004",
            "DPD_CTRL": "0x00000003",
            "expected_input_sample_count": f"0x{len(samples):08X}",
            "expected_dpd_sample_count": f"0x{len(samples):08X}",
            "expected_output_sample_count": f"0x{len(samples):08X}",
            "expected_error_status": "0x00000000",
            "expected_input_stall_count": "0x00000000",
        },
        "files": {},
    }
    for path in (input_out, coeff_out, expected_out, board_header):
        manifest["files"][path.name] = {"sha256": sha256(path), "bytes": path.stat().st_size}
    manifest["files"][args.header.name] = {"sha256": sha256(args.header), "bytes": args.header.stat().st_size}
    (args.out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="ascii")
    print(f"ILA_GOLDEN input={len(samples)} rf={index} package={args.package_index} out={args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
