#!/usr/bin/env python3
"""Generate C and synthesizable Verilog from a frozen TinyML tree JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


FEATURE_COUNT = 13


def leaves(node: dict[str, object]) -> list[dict[str, object]]:
    if "feature" not in node:
        return [node]
    return leaves(node["left"]) + leaves(node["right"])


def c_condition(bounds: list[list[int]], prefix: str = "input->feature_q20") -> str:
    return " &&\n      ".join(
        f"({prefix}[{index}] >= {bound[0]}) && ({prefix}[{index}] <= {bound[1]})"
        for index, bound in enumerate(bounds)
    )


def emit_c_tree(node: dict[str, object], indent: str = "  ") -> list[str]:
    if "feature" not in node:
        path = int(node["leaf_id"])
        length = len(str(node["path"]))
        output = [f"{indent}result.path = {path}u;",
                  f"{indent}result.path_length = {length}u;"]
        if int(node["action"]) != 6:
            output += [f"{indent}if (leaf_{path}_envelope(input)) {{",
                       f"{indent}  result.seed_package = {int(node['action'])}u;",
                       f"{indent}  result.direct = 1u;",
                       f"{indent}}} else {{",
                       f"{indent}  result.out_of_distribution = 1u;",
                       f"{indent}}}"]
        return output
    feature = int(node["feature"])
    threshold = int(node["threshold_q20"])
    output = [f"{indent}if (input->feature_q20[{feature}] <= {threshold}) {{"]
    output += emit_c_tree(node["left"], indent + "  ")
    output += [f"{indent}}} else {{"]
    output += emit_c_tree(node["right"], indent + "  ")
    output += [f"{indent}}}"]
    return output


def generate_c(model: dict[str, object]) -> str:
    released = [leaf for leaf in leaves(model["tree"]) if int(leaf["action"]) != 6]
    lines = [
        "/* Generated by generate_memory_tinyml_tree_sources.py; do not edit. */",
        '#include "dpd_tinyml_tree.h"', "",
        "static const int32_t feature_min_q20[DPD_TINYML_FEATURE_COUNT] = {",
        "  " + ", ".join(str(bound[0]) for bound in model["feature_bounds_q20"]),
        "};", "",
        "static const int32_t feature_max_q20[DPD_TINYML_FEATURE_COUNT] = {",
        "  " + ", ".join(str(bound[1]) for bound in model["feature_bounds_q20"]),
        "};", "",
    ]
    for leaf in released:
        path = int(leaf["leaf_id"])
        lines += [f"static int leaf_{path}_envelope(const dpd_tinyml_input_t *input) {{",
                  "  return " + c_condition(leaf["envelope_q20"]) + ";", "}", ""]
    lines += [
        "static int input_is_out_of_distribution(const dpd_tinyml_input_t *input) {",
        "  unsigned int index;", "",
        "  if ((input == 0) || (input->valid == 0u)) {", "    return 1;", "  }",
        "  for (index = 0; index < DPD_TINYML_FEATURE_COUNT; ++index) {",
        "    if ((input->feature_q20[index] < feature_min_q20[index]) ||",
        "        (input->feature_q20[index] > feature_max_q20[index])) {",
        "      return 1;", "    }", "  }", "  return 0;", "}", "",
        "dpd_tinyml_result_t dpd_tinyml_tree_predict(const dpd_tinyml_input_t *input) {",
        "  dpd_tinyml_result_t result = {",
        "    DPD_TINYML_FALLBACK_PACKAGE, 0u, 0u, 0u, 1u", "  };", "",
        "  if (input_is_out_of_distribution(input)) {", "    return result;", "  }",
        "  result.out_of_distribution = 0u;",
    ]
    lines += emit_c_tree(model["tree"])
    lines += ["  return result;", "}", ""]
    return "\n".join(lines)


def verilog_range(bounds: list[list[int]]) -> str:
    return " &&\n      ".join(
        f"(f{index} >= 32'sd{bound[0]}) && (f{index} <= 32'sd{bound[1]})"
        for index, bound in enumerate(bounds)
    )


def emit_verilog_tree(node: dict[str, object], indent: str = "      ") -> list[str]:
    if "feature" not in node:
        path = int(node["leaf_id"])
        length = len(str(node["path"]))
        output = [f"{indent}decision_path = 4'd{path};",
                  f"{indent}decision_path_length = 3'd{length};"]
        if int(node["action"]) != 6:
            output += [f"{indent}if (leaf_{path}_envelope) begin",
                       f"{indent}  seed_package = 3'd{int(node['action'])};",
                       f"{indent}  direct = 1'b1;",
                       f"{indent}end else begin",
                       f"{indent}  out_of_distribution = 1'b1;",
                       f"{indent}end"]
        return output
    feature = int(node["feature"])
    threshold = int(node["threshold_q20"])
    output = [f"{indent}if (f{feature} <= 32'sd{threshold}) begin"]
    output += emit_verilog_tree(node["left"], indent + "  ")
    output += [f"{indent}end else begin"]
    output += emit_verilog_tree(node["right"], indent + "  ")
    output += [f"{indent}end"]
    return output


def generate_verilog(model: dict[str, object]) -> str:
    released = [leaf for leaf in leaves(model["tree"]) if int(leaf["action"]) != 6]
    bounds = model["feature_bounds_q20"]
    lines = [
        "// Generated by generate_memory_tinyml_tree_sources.py; do not edit.",
        "`timescale 1ns/1ps", "`default_nettype none", "",
        "module dpd_tinyml_tree (", "  input wire feature_valid,",
        "  input wire signed [(13*32)-1:0] features_q20,",
        "  output reg [2:0] seed_package,", "  output reg direct,",
        "  output wire fallback_required,", "  output wire local_search_required,",
        "  output reg [3:0] decision_path,", "  output reg [2:0] decision_path_length,",
        "  output reg out_of_distribution", ");", "",
        "  localparam [2:0] FALLBACK_PACKAGE = 3'd6;", "",
    ]
    lines += [f"  wire signed [31:0] f{index} = features_q20[({index}*32) +: 32];"
              for index in range(FEATURE_COUNT)]
    lines += [""]
    for leaf in released:
        path = int(leaf["leaf_id"])
        lines += [f"  wire leaf_{path}_envelope =", "      " +
                  verilog_range(leaf["envelope_q20"]) + ";", ""]
    global_ood = " ||\n        ".join(
        f"(f{index} < 32'sd{bound[0]}) || (f{index} > 32'sd{bound[1]})"
        for index, bound in enumerate(bounds)
    )
    lines += [
        "  assign fallback_required = !direct;",
        "  assign local_search_required = !direct;", "",
        "  always @* begin", "    seed_package = FALLBACK_PACKAGE;",
        "    direct = 1'b0;", "    decision_path = 4'd0;",
        "    decision_path_length = 3'd0;",
        "    out_of_distribution = !feature_valid ||", "        " + global_ood + ";", "",
        "    if (!out_of_distribution) begin",
    ]
    lines += emit_verilog_tree(model["tree"])
    lines += ["    end", "  end", "", "endmodule", "", "`default_nettype wire", ""]
    return "\n".join(lines)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii", newline="\n") as handle:
        handle.write(content)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, required=True)
    parser.add_argument("--c-out", type=Path, required=True)
    parser.add_argument("--rtl-out", type=Path, required=True)
    args = parser.parse_args()
    with args.model.open(encoding="ascii") as handle:
        model = json.load(handle)["model"]
    write(args.c_out, generate_c(model))
    write(args.rtl_out, generate_verilog(model))
    print(f"Generated C and RTL for model 0x{int(model['model_version']):08x}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
