#!/usr/bin/env python3
"""Generate fixed-point PS-C constants for the frozen safety-first seed policy."""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from evaluate_memory_tinyml_loso import FALLBACK, PACKAGE_COUNT, read_conditions  # noqa: E402
from evaluate_memory_tinyml_safety_seed_policy import BLIND_PROFILE_IDS, assert_contract  # noqa: E402


Q20 = 1 << 20


def quantize(value: float) -> int:
    scaled = value * Q20
    return math.floor(scaled + 0.5) if scaled >= 0.0 else math.ceil(scaled - 0.5)


def stats(rows: list[dict[str, object]]) -> tuple[list[int], list[int]]:
    columns = list(zip(*(row["feature"] for row in rows)))
    center = [quantize(sum(column) / len(column)) for column in columns]
    # Constant monitor fields (for example no observed clip in this simulation
    # corpus) normalize to zero. Use one Q20 LSB so C never divides by zero.
    scale = [max(quantize(max(math.sqrt(sum((value - sum(column) / len(column)) ** 2
                                            for value in column) / max(len(column) - 1, 1)),
                                  1e-9)), 1)
             for column in columns]
    return center, scale


def normalize_q20(value: int, center: int, scale: int) -> int:
    delta = value - center
    magnitude = (abs(delta) * Q20 + scale // 2) // scale
    return -magnitude if delta < 0 else magnitude


def squared_distance(left: tuple[int, ...], right: tuple[int, ...]) -> int:
    return sum((a - b) ** 2 for a, b in zip(left, right))


def waveform_key(row: dict[str, object]) -> tuple[int, int, int]:
    return tuple(quantize(float(row["feature"][index])) for index in range(3))


def fixed_choice(evidence: list[dict[str, object]], feature_q20: tuple[int, ...],
                 center: list[int], scale: list[int], k: int,
                 max_distance_q20: int) -> tuple[int, int, int]:
    query_x = tuple(normalize_q20(value, midpoint, width)
                    for value, midpoint, width in zip(feature_q20, center, scale))
    target_waveform = feature_q20[:3]
    nearby = []
    for index, row in enumerate(evidence):
        if waveform_key(row) != target_waveform:
            continue
        row_q20 = tuple(quantize(float(value)) for value in row["feature"])
        row_x = tuple(normalize_q20(value, midpoint, width)
                      for value, midpoint, width in zip(row_q20, center, scale))
        nearby.append((squared_distance(query_x, row_x), index, row))
    nearby.sort(key=lambda item: (item[0], item[1]))
    if len(nearby) < k or nearby[0][0] > max_distance_q20 * max_distance_q20:
        return FALLBACK, 0, nearby[0][0] if nearby else 0
    nearest = nearby[:k]
    candidates = []
    for package in range(PACKAGE_COUNT):
        package_rows = [row["packages"][package] for _, _, row in nearest]
        if any(int(row["safe"]) == 0 for row in package_rows):
            continue
        candidates.append((sum(int(float(row["cost"])) for row in package_rows), package))
    if not candidates:
        return FALLBACK, 0, nearest[0][0]
    _, package = min(candidates)
    return package, k, nearest[0][0]


def write_header(path: Path, evidence: list[dict[str, object]], center: list[int],
                 scale: list[int], k: int, max_distance_q20: int) -> None:
    waveforms = sorted({waveform_key(row) for row in evidence})
    waveform_index = {value: index for index, value in enumerate(waveforms)}
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("#ifndef DPD_SAFETY_SEED_POLICY_H\n#define DPD_SAFETY_SEED_POLICY_H\n\n")
        handle.write("#include <stdint.h>\n#include \"dpd_tinyml_tree.h\"\n\n")
        handle.write("/* Generated by generate_memory_tinyml_safety_seed_policy.py; do not edit. */\n")
        handle.write("/* Blind PA profiles are excluded from all constants in this file. */\n")
        handle.write("#define DPD_SAFETY_SEED_POLICY_CONSTANTS_AVAILABLE 1U\n")
        handle.write("#define DPD_SAFETY_SEED_POLICY_BOARD_ENABLE_ALLOWED 0U\n")
        handle.write("#define DPD_SAFETY_SEED_POLICY_DIRECT_ALLOWED 0U\n")
        handle.write("#define DPD_SAFETY_SEED_POLICY_LOCAL_CANDIDATES 14U\n")
        handle.write(f"#define DPD_SAFETY_SEED_POLICY_EVIDENCE_ROWS {len(evidence)}U\n")
        handle.write(f"#define DPD_SAFETY_SEED_POLICY_WAVEFORMS {len(waveforms)}U\n")
        handle.write(f"#define DPD_SAFETY_SEED_POLICY_K {k}U\n")
        handle.write(f"#define DPD_SAFETY_SEED_POLICY_MAX_DISTANCE_Q20 {max_distance_q20}ULL\n\n")
        handle.write("typedef struct {\n  uint8_t waveform;\n  int32_t feature_q20[DPD_TINYML_FEATURE_COUNT];\n  uint8_t safe[6];\n  uint64_t cost[6];\n} dpd_safety_seed_evidence_t;\n\n")
        handle.write("typedef struct {\n  uint8_t seed_package;\n  uint8_t safety_qualified;\n  uint8_t safe_support;\n  uint8_t local_candidates;\n  uint64_t nearest_distance_sq_q40;\n} dpd_safety_seed_result_t;\n\n")
        handle.write("static const int32_t dsm_dpd_safety_seed_center_q20[DPD_TINYML_FEATURE_COUNT] = {\n  ")
        handle.write(", ".join(str(value) for value in center))
        handle.write("\n};\nstatic const int32_t dsm_dpd_safety_seed_scale_q20[DPD_TINYML_FEATURE_COUNT] = {\n  ")
        handle.write(", ".join(str(value) for value in scale))
        handle.write("\n};\nstatic const int32_t dsm_dpd_safety_seed_waveform_q20[DPD_SAFETY_SEED_POLICY_WAVEFORMS][3] = {\n")
        for waveform in waveforms:
            handle.write(f"  {{{waveform[0]}, {waveform[1]}, {waveform[2]}}},\n")
        handle.write("};\nstatic const dpd_safety_seed_evidence_t dsm_dpd_safety_seed_evidence[DPD_SAFETY_SEED_POLICY_EVIDENCE_ROWS] = {\n")
        for row in evidence:
            feature = [quantize(float(value)) for value in row["feature"]]
            safe = [int(row["packages"][package]["safe"]) for package in range(PACKAGE_COUNT)]
            cost = [int(float(row["packages"][package]["cost"])) for package in range(PACKAGE_COUNT)]
            handle.write("  {" + str(waveform_index[waveform_key(row)]) + ", {" +
                         ", ".join(str(value) for value in feature) + "}, {" +
                         ", ".join(str(value) for value in safe) + "}, {" +
                         ", ".join(str(value) + "ULL" for value in cost) + "}},\n")
        handle.write("};\n\n")
        handle.write("dpd_safety_seed_result_t dpd_safety_seed_policy_predict(const dpd_tinyml_input_t *input);\n\n")
        handle.write("#endif /* DPD_SAFETY_SEED_POLICY_H */\n")


def write_vectors(path: Path, evidence: list[dict[str, object]], test: list[dict[str, object]],
                  center: list[int], scale: list[int], k: int, max_distance_q20: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("name valid feature_q20[13] expected_package qualified support nearest_distance_sq_q40\n")
        for row in test:
            feature = tuple(quantize(float(value)) for value in row["feature"])
            package, support, nearest = fixed_choice(evidence, feature, center, scale, k, max_distance_q20)
            name = str(row["condition_id"])
            handle.write(f"{name} 1 " + " ".join(str(value) for value in feature) +
                         f" {package} {int(package != FALLBACK)} {support} {nearest}\n")


def compare_blind_decisions(path: Path, evidence: list[dict[str, object]],
                            blind: list[dict[str, object]], center: list[int],
                            scale: list[int], k: int, max_distance_q20: int) -> int:
    with path.open(newline="", encoding="ascii") as handle:
        expected = {row["condition_id"]: int(row["selected_seed"])
                    for row in csv.DictReader(handle)}
    if set(expected) != {str(row["condition_id"]) for row in blind}:
        raise ValueError("Blind decision evidence does not exactly match the frozen blind set")
    mismatches = []
    for row in blind:
        feature = tuple(quantize(float(value)) for value in row["feature"])
        package, _, _ = fixed_choice(evidence, feature, center, scale, k,
                                     max_distance_q20)
        if package != expected[str(row["condition_id"])]:
            mismatches.append(str(row["condition_id"]))
    if mismatches:
        raise ValueError(f"Quantized constants change frozen blind decisions: {mismatches[:4]}")
    return len(expected)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-train", type=Path, required=True)
    parser.add_argument("--development", type=Path, required=True)
    parser.add_argument("--blind", type=Path, required=True)
    parser.add_argument("--policy-report", type=Path, required=True)
    parser.add_argument("--blind-decisions", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--vectors", type=Path, required=True)
    parser.add_argument("--summary", type=Path, required=True)
    args = parser.parse_args()
    base = read_conditions(args.base_train)
    development = read_conditions(args.development)
    blind = read_conditions(args.blind)
    assert_contract(base, development, blind)
    report = json.loads(args.policy_report.read_text(encoding="ascii"))
    if report["blind_profile_ids"] != sorted(BLIND_PROFILE_IDS) or report["blind_data_used_for_selection"]:
        raise ValueError("Policy report does not preserve the blind-data contract")
    if not report["promotion_allowed"] or report["direct_execution_allowed"]:
        raise ValueError("Only promoted, no-direct safety policy reports may generate PS constants")
    k = int(report["selected_hyperparameters"]["k"])
    max_distance = report["selected_hyperparameters"]["max_distance"]
    if k != 7 or max_distance is None or float(max_distance) <= 0.0:
        raise ValueError("Expected frozen finite safety policy hyperparameters")
    evidence = base + development
    center, scale = stats(evidence)
    max_distance_q20 = quantize(float(max_distance))
    write_header(args.header, evidence, center, scale, k, max_distance_q20)
    write_vectors(args.vectors, evidence, evidence + blind, center, scale, k, max_distance_q20)
    blind_decision_count = compare_blind_decisions(args.blind_decisions, evidence,
                                                   blind, center, scale, k,
                                                   max_distance_q20)
    summary = {
        "policy": report["policy"],
        "evidence_rows": len(evidence),
        "development_profiles": len({str(row["profile_id"]) for row in development}),
        "base_profiles": len({str(row["profile_id"]) for row in base}),
        "blind_profiles_excluded_from_constants": sorted(BLIND_PROFILE_IDS),
        "vectors": len(evidence) + len(blind),
        "quantized_blind_decisions_checked": blind_decision_count,
        "quantized_blind_decision_mismatches": 0,
        "k": k,
        "max_distance_q20": max_distance_q20,
        "direct_execution_allowed": False,
        "board_enable_allowed": False,
        "mandatory_search_candidates": 14,
    }
    args.summary.parent.mkdir(parents=True, exist_ok=True)
    args.summary.write_text(json.dumps(summary, indent=2) + "\n", encoding="ascii")
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
