#!/usr/bin/env python3
"""Generate a deterministic Q1.15 QAM-OFDM input vector for the A53 DMA run."""

from __future__ import annotations

import argparse
import cmath
import math
import random
from pathlib import Path


DMA_WORDS = 4096


def qam_symbol(order: int, rng: random.Random) -> complex:
    width = math.isqrt(order)
    if width * width != order:
        raise ValueError("QAM order must be a square constellation size")
    i = 2 * rng.randrange(width) - width + 1
    q = 2 * rng.randrange(width) - width + 1
    return complex(i, q) / math.sqrt((2.0 / 3.0) * (order - 1))


def idft(bins: list[complex]) -> list[complex]:
    size = len(bins)
    return [sum(value * cmath.exp(2j * math.pi * index * tone / size)
                for tone, value in enumerate(bins)) / size
            for index in range(size)]


def generate(qam: int, used_subcarriers: int, input_backoff: float,
             fft_size: int, seed: int) -> list[int]:
    if fft_size <= 0 or fft_size % 2:
        raise ValueError("FFT size must be a positive even number")
    if not 0 < used_subcarriers < fft_size:
        raise ValueError("used subcarriers must be between 1 and FFT size - 1")
    if not 0 < input_backoff <= 1:
        raise ValueError("input backoff must be in (0, 1]")

    rng = random.Random(seed)
    values: list[complex] = []
    while len(values) < DMA_WORDS:
        bins = [0j] * fft_size
        lower = -(used_subcarriers // 2)
        upper = lower + used_subcarriers
        for subcarrier in range(lower, upper):
            if subcarrier != 0:
                bins[subcarrier % fft_size] = qam_symbol(qam, rng)
        values.extend(idft(bins))

    peak = max(abs(value) for value in values) or 1.0
    scale = input_backoff * 32767.0 / peak
    words: list[int] = []
    for value in values[:DMA_WORDS]:
        i = max(-32768, min(32767, round(value.real * scale)))
        q = max(-32768, min(32767, round(value.imag * scale)))
        words.append(((q & 0xFFFF) << 16) | (i & 0xFFFF))
    return words


def write_header(path: Path, words: list[int], args: argparse.Namespace) -> None:
    lines = [
        "#ifndef DSM_DPD_TX_WAVEFORM_H",
        "#define DSM_DPD_TX_WAVEFORM_H",
        "",
        "/* Generated by generate_dpd_tx_waveform.py; do not edit manually. */",
        "#define DSM_DPD_TX_WAVEFORM_AVAILABLE 1U",
        f"#define DSM_DPD_TX_WAVEFORM_QAM {args.qam}U",
        f"#define DSM_DPD_TX_WAVEFORM_USED_SUBCARRIERS {args.used_subcarriers}U",
        f"#define DSM_DPD_TX_WAVEFORM_INPUT_BACKOFF_PPM {round(args.input_backoff * 1000000)}U",
        f"#define DSM_DPD_TX_WAVEFORM_FFT_SIZE {args.fft_size}U",
        f"#define DSM_DPD_TX_WAVEFORM_SEED {args.seed}U",
        f"#define DSM_DPD_TX_WAVEFORM_WORDS {len(words)}U",
        "",
        "static const u32 dsm_dpd_tx_waveform_words[DSM_DPD_TX_WAVEFORM_WORDS] = {",
    ]
    for offset in range(0, len(words), 8):
        lines.append("    " + ", ".join(f"0x{word:08X}U" for word in words[offset:offset + 8]) + ",")
    lines.extend(["};", "", "#endif /* DSM_DPD_TX_WAVEFORM_H */", ""])
    path.write_text("\n".join(lines), encoding="ascii")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--qam", type=int, required=True)
    parser.add_argument("--used-subcarriers", type=int, required=True)
    parser.add_argument("--input-backoff", type=float, required=True)
    parser.add_argument("--fft-size", type=int, default=256)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--header", type=Path, required=True)
    args = parser.parse_args()
    words = generate(args.qam, args.used_subcarriers, args.input_backoff, args.fft_size, args.seed)
    args.header.parent.mkdir(parents=True, exist_ok=True)
    write_header(args.header, words, args)
    print(f"Generated {len(words)} Q1.15 DMA words: {args.header}")


if __name__ == "__main__":
    main()
