import os
import shutil
import socket
import vitis


repo_root = os.environ["DSM_REPO_ROOT"]
xsa_path = os.environ["DSM_XSA"]
workspace_path = os.environ["DSM_VITIS_WS"]

platform_name = "dsm_zu15eg_platform"
domain_name = "standalone_a53_0"
app_name = "dsm_dpd_baremetal_smoke"
src_dir = os.path.join(repo_root, "fpga", "zu15eg", "baremetal", "src")
define_text = os.environ.get("DSM_CAL_DEFINES", "")

print(f"Workspace: {workspace_path}")
print(f"XSA:       {xsa_path}")
print(f"Sources:   {src_dir}")
print(f"Defines:   {define_text}")


def select_vitis_server_port():
    """Avoid Vitis 2024.1 parsing Windows launcher output for a random port."""
    requested = int(os.environ.get("DSM_VITIS_SERVER_PORT", "0"))
    if requested:
        return requested
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]

if os.path.isdir(workspace_path):
    shutil.rmtree(workspace_path)
os.makedirs(workspace_path, exist_ok=True)

server_port = select_vitis_server_port()
print(f"Vitis server port: {server_port}")
client = vitis.create_client(port=server_port)
client.set_workspace(workspace_path)
platform = client.create_platform_component(
    name=platform_name,
    hw_design=xsa_path,
    domain_name=domain_name,
    cpu="psu_cortexa53_0",
    os="standalone",
)
platform.build()

platform_xpfm = client.find_platform_in_repos(platform_name)
app = client.create_app_component(
    name=app_name,
    platform=platform_xpfm,
    domain=domain_name,
    # Vitis 2024.1 registers the standalone blank project as
    # "empty_application".  The previous "empty" identifier was accepted by
    # older flows but is not a valid 2024.1 template.
    template="empty_application",
)
config_path = os.path.join(src_dir, "cal_config.h")
if define_text:
    defines = [item.strip() for item in define_text.split(";") if item.strip()]
    with open(config_path, "w", encoding="ascii") as f:
        f.write("#ifndef DSM_CAL_CONFIG_H\n")
        f.write("#define DSM_CAL_CONFIG_H\n\n")
        f.write("/* Generated by build_baremetal_smoke.ps1 -Define. */\n")
        for item in defines:
            if "=" in item:
                name, value = item.split("=", 1)
                f.write(f"#define {name.strip()} {value.strip()}\n")
            else:
                f.write(f"#define {item} 1\n")
        f.write("\n#endif /* DSM_CAL_CONFIG_H */\n")
elif os.path.exists(config_path):
    os.remove(config_path)

import_files = [
    "dsm_dpd_baremetal_smoke.c", "dpd_coeffs.h",
    "dpd_tinyml_tree.h", "dpd_tinyml_tree.c", "dpd_tinyml_features.c",
    "dpd_tinyml_hierarchy_policy.h",
]
safety_policy_header = os.path.join(src_dir, "dpd_safety_seed_policy.h")
safety_policy_source = os.path.join(src_dir, "dpd_safety_seed_policy.c")
if os.path.exists(safety_policy_header) and os.path.exists(safety_policy_source):
    import_files.extend(["dpd_safety_seed_policy.h", "dpd_safety_seed_policy.c"])
seed_path = os.path.join(src_dir, "dpd_seed.h")
if os.path.exists(seed_path):
    import_files.append("dpd_seed.h")
policy_path = os.path.join(src_dir, "dpd_trace_policy.h")
if os.path.exists(policy_path):
    import_files.append("dpd_trace_policy.h")
ai_policy_path = os.path.join(src_dir, "dpd_ai_policy.h")
if os.path.exists(ai_policy_path):
    import_files.append("dpd_ai_policy.h")
tinyml_lut_path = os.path.join(src_dir, "dpd_tinyml_lut_v2.h")
if os.path.exists(tinyml_lut_path):
    import_files.append("dpd_tinyml_lut_v2.h")
tinyml_packages_path = os.path.join(src_dir, "dpd_tinyml_packages_v2.h")
if os.path.exists(tinyml_packages_path):
    import_files.append("dpd_tinyml_packages_v2.h")
waveform_path = os.path.join(src_dir, "dpd_tx_waveform.h")
if os.path.exists(waveform_path):
    import_files.append("dpd_tx_waveform.h")
ila_golden_path = os.path.join(src_dir, "ila_golden_waveform.h")
if os.path.exists(ila_golden_path):
    import_files.append("ila_golden_waveform.h")
if os.path.exists(config_path):
    import_files.append("cal_config.h")
app.import_files(
    from_loc=src_dir,
    files=import_files,
    dest_dir_in_cmp="src",
)
app.build()
vitis.dispose()
