#ifndef DSM_DPD_SEED_H
#define DSM_DPD_SEED_H

/* Generated by generate_dpd_seed_table.py; do not edit manually. */
#define DSM_DPD_SEED_AVAILABLE 1U
#define DSM_DPD_SEED_PACKAGE_IDX 3U
#define DSM_DPD_SEED_C1_WORD 0x00A24002U
#define DSM_DPD_SEED_C3_WORD 0xF68216A1U
#define DSM_DPD_SEED_C5_WORD 0xF36517D0U

#endif /* DSM_DPD_SEED_H */
