#ifndef DSM_DPD_COEFFS_H
#define DSM_DPD_COEFFS_H

#include "xil_types.h"

/* Generated by matlab/dpd/export_dpd_coeff_header.m */
/* Default scenario: pa_nominal_16qam_48sc_bo058 */

#define DSM_DPD_C1_WORD 0xFFF93FCDU
#define DSM_DPD_C3_WORD 0xF21A1EC1U
#define DSM_DPD_C5_WORD 0xDD023CA8U

#define DSM_DPD_LUT_LEN 16U
static const u32 dsm_dpd_lut_words[DSM_DPD_LUT_LEN] = {
    0xFFF3401DU,
    0xFFC5407FU,
    0xFF714132U,
    0xFEEF4242U,
    0xFE49439AU,
    0xFD854527U,
    0xFCA146EFU,
    0xFAED4A4CU,
    0xFAED4A4CU,
    0xFAED4A4CU,
    0xFAED4A4CU,
    0xFAED4A4CU,
    0xFAED4A4CU,
    0xFAED4A4CU,
    0xFAED4A4CU,
    0xFAED4A4CU
};

#define DSM_DPD_NUM_PACKAGES 6U
static const u32 dsm_dpd_c1_words[DSM_DPD_NUM_PACKAGES] = {
    0xFFF93FCDU,
    0x0034405BU,
    0xFE593FE0U,
    0x00A24002U,
    0xFFF93FCEU,
    0xFFFD4006U
};

static const u32 dsm_dpd_c3_words[DSM_DPD_NUM_PACKAGES] = {
    0xF21A1EC1U,
    0xF2D41CEEU,
    0xEE1F260EU,
    0xF68216A1U,
    0xF1EF1ED7U,
    0xF16C201FU
};

static const u32 dsm_dpd_c5_words[DSM_DPD_NUM_PACKAGES] = {
    0xDD023CA8U,
    0xD92F46F0U,
    0x8C6D7FFFU,
    0xF36517D0U,
    0xDCB03DC8U,
    0xDFAF3742U
};

static const char *const dsm_dpd_package_names[DSM_DPD_NUM_PACKAGES] = {
    "pa_nominal_16qam_48sc_bo058",
    "pa_nominal_16qam_48sc_bo070",
    "pa_strong_16qam_48sc_bo058",
    "pa_weak_16qam_48sc_bo058",
    "pa_nominal_64qam_48sc_bo058",
    "pa_nominal_16qam_96sc_bo052"
};

/* EVM proxy is stored as round(EVM_percent * 10000), so 1.0% is 10000. */
static const u32 dsm_dpd_poly_evm_ppm[DSM_DPD_NUM_PACKAGES] = {
    819U,
    9783U,
    5671U,
    216U,
    973U,
    422U
};

static const u32 dsm_dpd_lut_evm_ppm[DSM_DPD_NUM_PACKAGES] = {
    13027U,
    16882U,
    21443U,
    7772U,
    14860U,
    11298U
};

static const u32 dsm_dpd_poly_sndr_mdB[DSM_DPD_NUM_PACKAGES] = {
    61739U,
    40190U,
    44926U,
    73318U,
    60236U,
    67488U
};

static const u32 dsm_dpd_lut_sndr_mdB[DSM_DPD_NUM_PACKAGES] = {
    37703U,
    35451U,
    33374U,
    42189U,
    36559U,
    38940U
};

static const u32 dsm_dpd_lut_packages[DSM_DPD_NUM_PACKAGES][DSM_DPD_LUT_LEN] = {
    {
        0xFFF3401DU,
        0xFFC5407FU,
        0xFF714132U,
        0xFEEF4242U,
        0xFE49439AU,
        0xFD854527U,
        0xFCA146EFU,
        0xFAED4A4CU,
        0xFAED4A4CU,
        0xFAED4A4CU,
        0xFAED4A4CU,
        0xFAED4A4CU,
        0xFAED4A4CU,
        0xFAED4A4CU,
        0xFAED4A4CU,
        0xFAED4A4CU
    },
    {
        0xFFF2401EU,
        0xFFC5407FU,
        0xFF724131U,
        0xFEED4248U,
        0xFE3243C8U,
        0xFD6B455CU,
        0xFC1F47F0U,
        0xFB644962U,
        0xF8804F2CU,
        0xF8804F2CU,
        0xF8804F2CU,
        0xF8804F2CU,
        0xF8804F2CU,
        0xF8804F2CU,
        0xF8804F2CU,
        0xF8804F2CU
    },
    {
        0xFEA34022U,
        0xFE5F40A3U,
        0xFDD9419DU,
        0xFCFE4326U,
        0xFBDF4518U,
        0xFA70477CU,
        0xF8C14A2AU,
        0xF5AC4ED4U,
        0xF5AC4ED4U,
        0xF5AC4ED4U,
        0xF5AC4ED4U,
        0xF5AC4ED4U,
        0xF5AC4ED4U,
        0xF5AC4ED4U,
        0xF5AC4ED4U,
        0xF5AC4ED4U
    },
    {
        0x009B4014U,
        0x007F4055U,
        0x004C40CDU,
        0xFFF9418EU,
        0xFFA54250U,
        0xFF3D433DU,
        0xFEAE4480U,
        0xFDA546CBU,
        0xFDA546CBU,
        0xFDA546CBU,
        0xFDA546CBU,
        0xFDA546CBU,
        0xFDA546CBU,
        0xFDA546CBU,
        0xFDA546CBU,
        0xFDA546CBU
    },
    {
        0xFFF2401FU,
        0xFFC5407EU,
        0xFF714132U,
        0xFEF3423BU,
        0xFE46439FU,
        0xFD644568U,
        0xFC5A477BU,
        0xFACA4A91U,
        0xFACA4A91U,
        0xFACA4A91U,
        0xFACA4A91U,
        0xFACA4A91U,
        0xFACA4A91U,
        0xFACA4A91U,
        0xFACA4A91U,
        0xFACA4A91U
    },
    {
        0xFFF2401FU,
        0xFFC44081U,
        0xFF74412DU,
        0xFF004221U,
        0xFE47439EU,
        0xFDA344EBU,
        0xFC954708U,
        0xFC954708U,
        0xFC954708U,
        0xFC954708U,
        0xFC954708U,
        0xFC954708U,
        0xFC954708U,
        0xFC954708U,
        0xFC954708U,
        0xFC954708U
    }
};

#endif /* DSM_DPD_COEFFS_H */
