#ifndef DPD_TINYML_LUT_V2_H
#define DPD_TINYML_LUT_V2_H

/* Generated by generate_memory_tinyml_lut_header.py; do not edit. */
#define DPD_TINYML_LUT_V2_AVAILABLE 1U
#define DPD_TINYML_LUT_V2_ROWS 8U

static const unsigned dsm_dpd_tinyml_lut_v2[DPD_TINYML_LUT_V2_ROWS][4] = {
    {16U, 20000U, 580000U, 1U},
    {16U, 20000U, 700000U, 5U},
    {16U, 40000U, 580000U, 1U},
    {16U, 40000U, 700000U, 5U},
    {64U, 20000U, 580000U, 1U},
    {64U, 20000U, 700000U, 5U},
    {64U, 40000U, 580000U, 1U},
    {64U, 40000U, 700000U, 5U},
};

#endif /* DPD_TINYML_LUT_V2_H */
