/* Generated by generate_memory_tinyml_tree_sources.py; do not edit. */
#include "dpd_tinyml_tree.h"

static const int32_t feature_min_q20[DPD_TINYML_FEATURE_COUNT] = {
  262144, 524288, 608174, 308405, 1054364, 2187435, 38822, 347382, 1568684, 15807, 0, 0, 38822
};

static const int32_t feature_max_q20[DPD_TINYML_FEATURE_COUNT] = {
  1048576, 1048576, 734003, 1048576, 1070144, 3171213, 105054, 386375, 105200450, 436535, 0, 0, 105054
};

static int leaf_0_envelope(const dpd_tinyml_input_t *input) {
  return (input->feature_q20[0] >= 262144) && (input->feature_q20[0] <= 1048576) &&
      (input->feature_q20[1] >= 524288) && (input->feature_q20[1] <= 1048576) &&
      (input->feature_q20[2] >= 608174) && (input->feature_q20[2] <= 608174) &&
      (input->feature_q20[3] >= 308405) && (input->feature_q20[3] <= 1048576) &&
      (input->feature_q20[4] >= 1054364) && (input->feature_q20[4] <= 1064422) &&
      (input->feature_q20[5] >= 2320750) && (input->feature_q20[5] <= 3171213) &&
      (input->feature_q20[6] >= 38822) && (input->feature_q20[6] <= 92686) &&
      (input->feature_q20[7] >= 349216) && (input->feature_q20[7] <= 386375) &&
      (input->feature_q20[8] >= 2064775) && (input->feature_q20[8] <= 59310860) &&
      (input->feature_q20[9] >= 22610) && (input->feature_q20[9] <= 389807) &&
      (input->feature_q20[10] >= 0) && (input->feature_q20[10] <= 0) &&
      (input->feature_q20[11] >= 0) && (input->feature_q20[11] <= 0) &&
      (input->feature_q20[12] >= 38822) && (input->feature_q20[12] <= 92686);
}

static int leaf_11_envelope(const dpd_tinyml_input_t *input) {
  return (input->feature_q20[0] >= 1048576) && (input->feature_q20[0] <= 1048576) &&
      (input->feature_q20[1] >= 524288) && (input->feature_q20[1] <= 524288) &&
      (input->feature_q20[2] >= 734003) && (input->feature_q20[2] <= 734003) &&
      (input->feature_q20[3] >= 308405) && (input->feature_q20[3] <= 1048576) &&
      (input->feature_q20[4] >= 1061107) && (input->feature_q20[4] <= 1066450) &&
      (input->feature_q20[5] >= 2495721) && (input->feature_q20[5] <= 2653496) &&
      (input->feature_q20[6] >= 52420) && (input->feature_q20[6] <= 97863) &&
      (input->feature_q20[7] >= 361357) && (input->feature_q20[7] <= 367264) &&
      (input->feature_q20[8] >= 3728765) && (input->feature_q20[8] <= 5592713) &&
      (input->feature_q20[9] >= 151299) && (input->feature_q20[9] <= 353921) &&
      (input->feature_q20[10] >= 0) && (input->feature_q20[10] <= 0) &&
      (input->feature_q20[11] >= 0) && (input->feature_q20[11] <= 0) &&
      (input->feature_q20[12] >= 52420) && (input->feature_q20[12] <= 97863);
}

static int input_is_out_of_distribution(const dpd_tinyml_input_t *input) {
  unsigned int index;

  if ((input == 0) || (input->valid == 0u)) {
    return 1;
  }
  for (index = 0; index < DPD_TINYML_FEATURE_COUNT; ++index) {
    if ((input->feature_q20[index] < feature_min_q20[index]) ||
        (input->feature_q20[index] > feature_max_q20[index])) {
      return 1;
    }
  }
  return 0;
}

dpd_tinyml_result_t dpd_tinyml_tree_predict(const dpd_tinyml_input_t *input) {
  dpd_tinyml_result_t result = {
    DPD_TINYML_FALLBACK_PACKAGE, 0u, 0u, 0u, 1u
  };

  if (input_is_out_of_distribution(input)) {
    return result;
  }
  result.out_of_distribution = 0u;
  if (input->feature_q20[2] <= 608174) {
    result.path = 0u;
    result.path_length = 1u;
    if (leaf_0_envelope(input)) {
      result.seed_package = 1u;
      result.direct = 1u;
    } else {
      result.out_of_distribution = 1u;
    }
  } else {
    if (input->feature_q20[8] <= 5592713) {
      if (input->feature_q20[0] <= 262144) {
        result.path = 4u;
        result.path_length = 3u;
      } else {
        if (input->feature_q20[7] <= 355196) {
          result.path = 10u;
          result.path_length = 4u;
        } else {
          result.path = 11u;
          result.path_length = 4u;
          if (leaf_11_envelope(input)) {
            result.seed_package = 4u;
            result.direct = 1u;
          } else {
            result.out_of_distribution = 1u;
          }
        }
      }
    } else {
      if (input->feature_q20[6] <= 81615) {
        if (input->feature_q20[7] <= 354048) {
          result.path = 12u;
          result.path_length = 4u;
        } else {
          result.path = 13u;
          result.path_length = 4u;
        }
      } else {
        result.path = 7u;
        result.path_length = 3u;
      }
    }
  }
  return result;
}
