function header_path = export_dpd_coeff_header(varargin)
% export_dpd_coeff_header
% Export fixed-point DPD coefficients from the MATLAB calibration sweep to a
% C header for Vitis bare-metal experiments.

  cfg = struct();
  cfg.scenario_index = 1;
  cfg.export_all = true;
  cfg.out_path = fullfile(fileparts(fileparts(fileparts(mfilename('fullpath')))), ...
    'fpga', 'zu15eg', 'baremetal', 'src', 'dpd_coeffs.h');
  cfg = parse_kv(cfg, varargin{:});

  [T, D] = run_ai_assisted_dpd_sweep();
  if cfg.scenario_index < 1 || cfg.scenario_index > height(T)
    error('scenario_index out of range.');
  end

  row = T(cfg.scenario_index, :);
  if cfg.export_all
    idx_list = 1:height(T);
  else
    idx_list = cfg.scenario_index;
  end
  out_dir = fileparts(cfg.out_path);
  if ~exist(out_dir, 'dir')
    mkdir(out_dir);
  end

  fid = fopen(cfg.out_path, 'w');
  if fid < 0
    error('Cannot write %s', cfg.out_path);
  end
  cleanup = onCleanup(@() fclose(fid));

  fprintf(fid, '#ifndef DSM_DPD_COEFFS_H\n');
  fprintf(fid, '#define DSM_DPD_COEFFS_H\n\n');
  fprintf(fid, '#include "xil_types.h"\n\n');
  fprintf(fid, '/* Generated by matlab/dpd/export_dpd_coeff_header.m */\n');
  fprintf(fid, '/* Default scenario: %s */\n\n', row.Scenario);
  fprintf(fid, '#define DSM_DPD_C1_WORD %sU\n', row.C1_hex);
  fprintf(fid, '#define DSM_DPD_C3_WORD %sU\n', row.C3_hex);
  fprintf(fid, '#define DSM_DPD_C5_WORD %sU\n\n', row.C5_hex);
  fprintf(fid, '#define DSM_DPD_LUT_LEN 16U\n');
  fprintf(fid, 'static const u32 dsm_dpd_lut_words[DSM_DPD_LUT_LEN] = {\n');
  for k = 1:16
    word = char(D.lut_words(cfg.scenario_index, k));
    suffix = ',';
    if k == 16
      suffix = '';
    end
    fprintf(fid, '    %sU%s\n', word, suffix);
  end
  fprintf(fid, '};\n\n');

  fprintf(fid, '#define DSM_DPD_NUM_PACKAGES %dU\n', numel(idx_list));
  fprintf(fid, 'static const u32 dsm_dpd_c1_words[DSM_DPD_NUM_PACKAGES] = {\n');
  write_word_array(fid, T.C1_hex(idx_list));
  fprintf(fid, '};\n\n');
  fprintf(fid, 'static const u32 dsm_dpd_c3_words[DSM_DPD_NUM_PACKAGES] = {\n');
  write_word_array(fid, T.C3_hex(idx_list));
  fprintf(fid, '};\n\n');
  fprintf(fid, 'static const u32 dsm_dpd_c5_words[DSM_DPD_NUM_PACKAGES] = {\n');
  write_word_array(fid, T.C5_hex(idx_list));
  fprintf(fid, '};\n\n');
  fprintf(fid, 'static const char *const dsm_dpd_package_names[DSM_DPD_NUM_PACKAGES] = {\n');
  for ii = 1:numel(idx_list)
    row_idx = idx_list(ii);
    suffix = ',';
    if ii == numel(idx_list)
      suffix = '';
    end
    fprintf(fid, '    "%s"%s\n', char(T.Scenario(row_idx)), suffix);
  end
  fprintf(fid, '};\n\n');
  fprintf(fid, '/* EVM proxy is stored as round(EVM_percent * 10000), so 1.0%% is 10000. */\n');
  fprintf(fid, 'static const u32 dsm_dpd_poly_evm_ppm[DSM_DPD_NUM_PACKAGES] = {\n');
  write_u32_array(fid, round(T.FixedDPD_EVM_percent(idx_list) * 10000));
  fprintf(fid, '};\n\n');
  fprintf(fid, 'static const u32 dsm_dpd_lut_evm_ppm[DSM_DPD_NUM_PACKAGES] = {\n');
  write_u32_array(fid, round(T.LUTDPD_EVM_percent(idx_list) * 10000));
  fprintf(fid, '};\n\n');
  fprintf(fid, 'static const u32 dsm_dpd_poly_sndr_mdB[DSM_DPD_NUM_PACKAGES] = {\n');
  write_u32_array(fid, round(T.FixedDPD_SNDR_dB(idx_list) * 1000));
  fprintf(fid, '};\n\n');
  fprintf(fid, 'static const u32 dsm_dpd_lut_sndr_mdB[DSM_DPD_NUM_PACKAGES] = {\n');
  write_u32_array(fid, round(T.LUTDPD_SNDR_dB(idx_list) * 1000));
  fprintf(fid, '};\n\n');
  fprintf(fid, 'static const u32 dsm_dpd_lut_packages[DSM_DPD_NUM_PACKAGES][DSM_DPD_LUT_LEN] = {\n');
  for ii = 1:numel(idx_list)
    row_idx = idx_list(ii);
    fprintf(fid, '    {\n');
    for jj = 1:16
      suffix = ',';
      if jj == 16
        suffix = '';
      end
      fprintf(fid, '        %sU%s\n', char(D.lut_words(row_idx, jj)), suffix);
    end
    suffix = ',';
    if ii == numel(idx_list)
      suffix = '';
    end
    fprintf(fid, '    }%s\n', suffix);
  end
  fprintf(fid, '};\n\n');
  fprintf(fid, '#endif /* DSM_DPD_COEFFS_H */\n');

  header_path = cfg.out_path;
  fprintf('Wrote %s\n', header_path);
end

function write_word_array(fid, words)
  for k = 1:numel(words)
    suffix = ',';
    if k == numel(words)
      suffix = '';
    end
    fprintf(fid, '    %sU%s\n', char(words(k)), suffix);
  end
end

function write_u32_array(fid, values)
  for k = 1:numel(values)
    suffix = ',';
    if k == numel(values)
      suffix = '';
    end
    fprintf(fid, '    %dU%s\n', uint32(values(k)), suffix);
  end
end

function cfg = parse_kv(cfg, varargin)
  if mod(numel(varargin), 2) ~= 0
    error('Arguments must be key/value pairs.');
  end
  for k = 1:2:numel(varargin)
    key = varargin{k};
    if ~isfield(cfg, key)
      error('Unknown option: %s', key);
    end
    cfg.(key) = varargin{k+1};
  end
end
