function prepare_lpdsmdpa_bpf_dpd_bittrue_vectors(varargin)
% Prepare release-gated LPDSM2 DPA+BPF Memory-Poly vectors for RTL signoff.
%
% The coefficient source is intentionally restricted to the quality-gated
% release table produced by run_lpdsmdpa_bpf_dpd_closed_loop. Diagnostic or
% candidate tables must never be used to program the RTL regression.

  cfg.n_input = 256;
  cfg.seed = 71;
  here = fileparts(mfilename('fullpath'));
  repo = fileparts(fileparts(here));
  cfg.release_file = fullfile(repo, 'matlab', 'out', 'dpd', ...
    'lpdsmdpa_bpf_dpd_release_coefficients.csv');
  cfg.quality_gate_file = fullfile(repo, 'matlab', 'out', 'dpd', ...
    'lpdsmdpa_bpf_dpd_quality_gate.csv');
  cfg.out_dir = fullfile(repo, 'matlab', 'out', 'dpd', ...
    'lpdsmdpa_bpf_bittrue');
  for n = 1:2:numel(varargin)
    cfg.(varargin{n}) = varargin{n + 1};
  end

  assert(exist(cfg.quality_gate_file, 'file') == 2, ...
    'Quality-gate result is missing: %s', cfg.quality_gate_file);
  assert(exist(cfg.release_file, 'file') == 2, ...
    'Release coefficient table is missing: %s', cfg.release_file);
  gate = readtable(cfg.quality_gate_file, 'TextType', 'string');
  assert(height(gate) == 1 && string(gate.Status(1)) == "ACCEPT", ...
    'The LPDSM2 DPA+BPF quality gate did not accept this coefficient package.');
  required_passes = {'ValidationEVMPassCount', 'ValidationSNDRPassCount', ...
    'ValidationOutOfBandPassCount', 'TestEVMPassCount', 'TestSNDRPassCount', ...
    'TestOutOfBandPassCount'};
  required_limits = {'ValidationQ214LimitCount', 'TestQ214LimitCount'};
  assert(all(ismember([required_passes required_limits], ...
    gate.Properties.VariableNames)), 'Quality-gate table has an unsupported format.');
  for n = 1:numel(required_passes)
    assert(gate.(required_passes{n})(1) == 3, ...
      'Quality-gate pass requirement failed: %s', required_passes{n});
  end
  for n = 1:numel(required_limits)
    assert(gate.(required_limits{n})(1) == 0, ...
      'Quality-gate limit requirement failed: %s', required_limits{n});
  end

  prepare_dpd_memory_poly_bittrue_vectors( ...
    'n_input', cfg.n_input, ...
    'seed', cfg.seed, ...
    'active_taps', 4, ...
    'coefficients_file', cfg.release_file, ...
    'out_dir', cfg.out_dir);

  fprintf(['LPDSM2 DPA+BPF release vectors prepared: %d samples, ' ...
    'source=%s\n'], cfg.n_input, cfg.release_file);
end
