#!/usr/bin/env python3
"""Analyze the local ADS TSMC40 DPA switch-core transient dataset.

The input dataset is generated by ``run_tsmc40_dpa_switch_core.py`` and is
ignored by Git.  Reported values are circuit-level pre-layout trends only;
they are not PDK signoff, PAE, ACLR, or final silicon claims.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
from keysight.ads import dds  # Import DDS before the dataset API.
from keysight.ads import dataset


REPO = Path(__file__).resolve().parents[2]
DEFAULT_RUN_DIR = REPO / "ads" / "low_power_dpa" / "simulation" / "tsmc40_dpa_switch_core_tt"


def normalized(name: str) -> str:
    return "".join(character for character in name.lower() if character.isalnum())


def column(frame, candidates: list[str]) -> np.ndarray:
    available = {normalized(name): name for name in frame.columns}
    for candidate in candidates:
        actual = available.get(normalized(candidate))
        if actual is not None:
            return frame[actual].to_numpy(dtype=float)
    raise KeyError(f"Missing one of {candidates}; dataset columns: {', '.join(frame.columns)}")


def time_average(time_s: np.ndarray, values: np.ndarray) -> float:
    return float(np.trapz(values, time_s) / (time_s[-1] - time_s[0]))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", type=Path, default=DEFAULT_RUN_DIR)
    parser.add_argument("--dataset", default="tsmc40_dpa_switch_core_tt.net.ds")
    parser.add_argument(
        "--observation-output",
        type=Path,
        help="Optional uniform observation CSV with time_s,vout_v,ivdd_a columns.",
    )
    parser.add_argument("--observation-sample-hz", type=float, default=1.0e9)
    args = parser.parse_args()

    dataset_path = args.run_dir.resolve() / args.dataset
    if not dataset_path.is_file():
        raise RuntimeError(f"ADS dataset not found: {dataset_path}")
    netlist_path = dataset_path.parent / "tsmc40_dpa_switch_core_tt.net"
    netlist_text = netlist_path.read_text(encoding="ascii") if netlist_path.is_file() else ""
    passive_model = "estimated" if "* Passive model: estimated" in netlist_text else "ideal"
    with dataset.open(dataset_path) as ds:
        frame = ds["TRAN1.TRAN"].to_dataframe()

    time_s = frame.index.to_numpy(dtype=float)
    sw_a = column(frame, ["swa", "v.swa"])
    sw_b = column(frame, ["swb", "v.swb"])
    sec_p = column(frame, ["secp", "v.secp"])
    vdd = column(frame, ["vdd", "v.vdd"])
    ivdd = column(frame, ["vddsrc.i", "i.vddsrc"])
    g_ap = column(frame, ["gap", "v.gap"])
    g_an = column(frame, ["gan", "v.gan"])
    g_bp = column(frame, ["gbp", "v.gbp"])
    g_bn = column(frame, ["gbn", "v.gbn"])

    bridge_diff = sw_a - sw_b
    output_power_w = time_average(time_s, sec_p**2 / 50.0)
    # HSPICE current through an independent supply is positive into its
    # positive terminal, hence power drawn from VDD is the negative product.
    dc_power_w = -time_average(time_s, vdd * ivdd)
    overlap_a = np.logical_and(g_ap < 0.6, g_an > 0.6)
    overlap_b = np.logical_and(g_bp < 0.6, g_bn > 0.6)
    metrics = {
        "samples": int(len(frame)),
        "duration_ns": float((time_s[-1] - time_s[0]) * 1.0e9),
        "bridge_diff_pp_v": float(np.ptp(bridge_diff)),
        "output_50ohm_pp_v": float(np.ptp(sec_p)),
        "output_50ohm_rms_v": float(np.sqrt(time_average(time_s, sec_p**2))),
        "output_50ohm_power_mw": 1.0e3 * output_power_w,
        "output_50ohm_power_dbm": float(10.0 * np.log10(output_power_w / 1.0e-3)) if output_power_w > 0.0 else None,
        "dc_power_mw": 1.0e3 * dc_power_w,
        "efficiency_trend_percent": float(100.0 * output_power_w / dc_power_w) if dc_power_w > 0.0 else None,
        "supply_current_mean_ma": 1.0e3 * time_average(time_s, -ivdd),
        "supply_current_peak_ma": 1.0e3 * float(np.max(-ivdd)),
        "leg_a_overlap_samples": int(np.count_nonzero(overlap_a)),
        "leg_b_overlap_samples": int(np.count_nonzero(overlap_b)),
        "measurement_plane": f"50 ohm single-ended {passive_model}-transformer secondary",
    }
    assert metrics["leg_a_overlap_samples"] == 0, "A bridge leg overlaps"
    assert metrics["leg_b_overlap_samples"] == 0, "B bridge leg overlaps"
    assert metrics["output_50ohm_pp_v"] > 1e-6, "50-ohm output is static"
    if args.observation_output is not None:
        if args.observation_sample_hz <= 0.0:
            raise RuntimeError("--observation-sample-hz must be positive.")
        count = int(np.floor((time_s[-1] - time_s[0]) * args.observation_sample_hz))
        if count < 32:
            raise RuntimeError("Observation window has fewer than 32 uniform samples.")
        edges_s = time_s[0] + np.arange(count + 1) / args.observation_sample_hz
        centers_s = 0.5 * (edges_s[:-1] + edges_s[1:])
        integral_as = np.concatenate((np.array([0.0]), np.cumsum(0.5 * (ivdd[1:] + ivdd[:-1]) * np.diff(time_s))))
        edge_integral_as = np.interp(edges_s, time_s, integral_as)
        observation = np.column_stack(
            (
                centers_s,
                np.interp(centers_s, time_s, sec_p),
                -np.diff(edge_integral_as) * args.observation_sample_hz,
            )
        )
        output = args.observation_output.resolve()
        output.parent.mkdir(parents=True, exist_ok=True)
        np.savetxt(output, observation, delimiter=",", header="time_s,vout_v,ivdd_a", comments="")
        metrics["observation_csv"] = str(output)
        metrics["observation_samples"] = count
    summary_path = dataset_path.parent / "analysis_summary.json"
    summary_path.write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(metrics, indent=2))
    print("ADS TSMC40 switch-core analysis PASS")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise
