% Full five-level 250-MHz three-seed acceptance with per-frame peak drive.
% This is a separate drive policy from fair-RMS: every OFDM frame is scaled
% without clipping to the same 0.35 DSM peak limit, so its average power may
% vary with PAPR.  Results must never be mixed with the fair-RMS acceptance.
addpath(fileparts(mfilename('fullpath')));
out_dir = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'out', ...
    'tid32_thermo5_fullchain_250_peaknorm_three_seed');
Summary = run_tid32_thermo5_profile_bandwidth_sweep( ...
    'profile_names', "mild", 'bandwidths_hz', 250e6, ...
    'seed_sets', [101 137 211; 307 349 401; 503 547 601], ...
    'fit_nsym', 12, 'val_nsym', 10, 'test_nsym', 12, ...
    'enable_dpd_training', false, 'bpf_passband_factor', 1.5, ...
    'input_normalization', "peak", 'write_outputs', true, ...
    'out_dir', out_dir);
identity = Summary(Summary.Mode == "identity_untrained", :);
assert(all(identity.RawWordMismatches == 0), 'Raw-stream contract mismatch.');
disp(identity);
