% Four-tap Q2.14 memory-DPD qualification at the accepted peak-drive point.
% It keeps the identical full chain and isolated 12/10/12-symbol seed sets
% used by the peak-normalized identity baseline.  The model itself applies
% validation and held-out gates; this entry never writes learned coefficients
% to RTL.
addpath(fileparts(mfilename('fullpath')));
out_dir = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'out', ...
    'tid32_thermo5_fullchain_250_peaknorm_memory_dpd_three_seed');
Summary = run_tid32_thermo5_profile_bandwidth_sweep( ...
    'profile_names', "mild", 'bandwidths_hz', 250e6, ...
    'seed_sets', [101 137 211; 307 349 401; 503 547 601], ...
    'fit_nsym', 12, 'val_nsym', 10, 'test_nsym', 12, ...
    'enable_dpd_training', true, 'dpd_active_taps', 4, ...
    'bpf_passband_factor', 1.5, 'input_normalization', "peak", ...
    'write_outputs', true, 'out_dir', out_dir);
assert(all(Summary.RawWordMismatches == 0), 'Raw-stream contract mismatch.');
disp(Summary);
