% Reproducible raw-Fs/4 feasibility sweep for the five-level TID candidate.
% This is deliberately a small, single-seed screen.  Passing it is not a
% deployment qualification; it merely selects points for isolated-seed and
% full-frontend DPA/BPF/DDC testing.
addpath(fileparts(mfilename('fullpath')));
out_dir=fullfile(fileparts(fileparts(mfilename('fullpath'))),'out', ...
    'tid32_receiver_contract_smoke','thermo5_sweep_fs4');
Summary=run_tid32_thermo5_step_sweep( ...
    'bandwidths_hz',[20e6 40e6 80e6 100e6 160e6], ...
    'steps',6144, ...
    'seeds',101, ...
    'nsym',4, ...
    'input_normalization',"fair_rms", ...
    'rms_drive',0.13, ...
    'receiver_mode',"fs4_ddc", ...
    'out_dir',out_dir);
disp(Summary);
