% Reproducible raw-Fs/4 three-seed acceptance for the five-level TID core.
% This validates the digital TID/FS4/DDC contract only.  It does not model
% DPA/BPF/DPD, four physical serializers, or a board-level RF path.
addpath(fileparts(mfilename('fullpath')));
out_dir = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'out', ...
    'tid32_thermo5_250mhz_three_seed_rawddc');
Summary = run_tid32_thermo5_step_sweep( ...
    'bandwidths_hz', 250e6, ...
    'steps', 7168, ...
    'seeds', [101 307 503], ...
    'nsym', 8, ...
    'input_normalization', "fair_rms", ...
    'rms_drive', 0.11, ...
    'receiver_mode', "fs4_ddc", ...
    'out_dir', out_dir);
assert(all(Summary.StreamMismatches == 0), 'Raw-stream contract mismatch.');
assert(all(Summary.Pass256QAM), 'One or more isolated seeds failed 256-QAM.');
disp(Summary);
