% Full five-level 250-MHz three-seed DPA/BPF/DDC identity-DPD acceptance.
% The profile is explicitly synthetic mild; it is not PA measurement data.
% RMS=0.095 is the maximum common no-clipping drive for all nine frames
% under the 0.35 peak contract.
% Use independent 12/10/12-symbol fit/validation/held-out frames.  Short
% 2/2/3 smoke frames are not an acceptance-quality channel estimate.
addpath(fileparts(mfilename('fullpath')));
out_dir = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'out', ...
    'tid32_thermo5_fullchain_250_mild_three_seed');
Summary = run_tid32_thermo5_profile_bandwidth_sweep( ...
    'profile_names', "mild", 'bandwidths_hz', 250e6, ...
    'seed_sets', [101 137 211; 307 349 401; 503 547 601], ...
    'fit_nsym', 12, 'val_nsym', 10, 'test_nsym', 12, ...
    'enable_dpd_training', false, 'bpf_passband_factor', 1.5, ...
    'input_normalization', "fair_rms", 'rms_drive', 0.095, ...
    'write_outputs', true, 'out_dir', out_dir);
identity = Summary(Summary.Mode == "identity_untrained", :);
assert(all(identity.RawWordMismatches == 0), 'Raw-stream contract mismatch.');
assert(all(identity.Pass256QAM), 'One or more mild-profile held-out seeds failed 256-QAM.');
disp(identity);
